// This file is auto generated by Teams Toolkit to provide you instructions and reference code to call your api.

/*
Your next steps:
1. Run npm install. If your project did not install @microsoft/teamsfx package before, we have added it to package.json for you.
   You need to run the command under "bot" folder instead of project's root folder.
2. Add your API Key to TEAMSFX_API_APIKEYPARAM_API_KEY in "bot/.env.teamsfx.local".

You can now import the API client (an Axios instance) in another file and call apiKeyParam APIs without worrying about authentication.
Here is an example for a GET request to "relative_path_of_target_api":
```
const { apiKeyParamClient } = require("relative_path_to_this_file");

const response = await apiKeyParamClient.get("relative_path_of_target_api");
// You only need to enter the relative path for your API.
// For example, if you want to call api https://my-api-endpoint/test, and inputted https://my-api-endpoint as API endpoint,
// the code will looks like: const response = await apiKeyParamClient.get("test");

const responseBody = response.data;
```

You can refer https://aka.ms/teamsfx-connect-api to learn more.
*/
const teamsfxSdk = require("@microsoft/teamsfx");

// Loads current app's configuration.
const teamsFx = new teamsfxSdk.TeamsFx();
// Initializes a new axios instance to call apiKeyParam API.
const authProvider = new teamsfxSdk.ApiKeyProvider(
  "user_inputted_query_param_name",
  teamsFx.getConfig("TEAMSFX_API_APIKEYPARAM_API_KEY"),
  teamsfxSdk.ApiKeyLocation.QueryParams
);
const apiKeyParamClient = teamsfxSdk.createApiClient(
  teamsFx.getConfig("TEAMSFX_API_APIKEYPARAM_ENDPOINT"),
  authProvider
);
module.exports.apiKeyParamClient = apiKeyParamClient;

/* 
Setting API configuration for cloud environment: 
We have already set the configuration to .env.teamsfx.local based on your answers. 
Before you deploy your code to cloud using TeamsFx, please follow https://aka.ms/teamsfx-add-appsettings to add following app settings with appropriate value to your Azure environment: 
TEAMSFX_API_APIKEYPARAM_ENDPOINT
TEAMSFX_API_APIKEYPARAM_API_KEY

You can refer https://aka.ms/teamsfx-connect-api to learn more. 
*/