// This file is auto generated by Teams Toolkit to provide you instructions and reference code to call your api.

/*
Your next steps:
1. Run npm install. If your project did not install @microsoft/teamsfx package before, we have added it to package.json for you.
   You need to run the command under "bot" folder instead of project's root folder.
2. Add code to read your cert content and replace "<your-cert>" and "<your-private-key>" with actual value.

You can now import the API client (an Axios instance) in another file and call cert APIs without worrying about authentication.
Here is an example for a GET request to "relative_path_of_target_api":
```
import { certClient } from "relative_path_to_this_file";

const response = await certClient.get("relative_path_of_target_api");
// You only need to enter the relative path for your API.
// For example, if you want to call api https://my-api-endpoint/test, and inputted https://my-api-endpoint as API endpoint,
// the code will looks like: const response = await certClient.get("test");

const responseBody = response.data;
```

You can refer https://aka.ms/teamsfx-connect-api to learn more.
*/
import {
  TeamsFx,
  createApiClient,
  CertificateAuthProvider,
  createPemCertOption,
} from "@microsoft/teamsfx";

// Loads current app's configuration.
const teamsFx = new TeamsFx();
// Initializes a new axios instance to call cert API.
const authProvider = new CertificateAuthProvider(
  // TODO: Please add code to read your cert and private key, replace "<your-cert>" and "<your-private-key>" with actual value.
  // If you have a .pfx cert, you can use "createPfxCertOption" function to initialize your cert option.
  createPemCertOption("<your-cert>", "<your-private-key>")
);
const certClient = createApiClient(teamsFx.getConfig("TEAMSFX_API_CERT_ENDPOINT"), authProvider);
export { certClient };

/* 
Setting API configuration for cloud environment: 
We have already set the configuration to .env.teamsfx.local based on your answers. 
Before you deploy your code to cloud using TeamsFx, please follow https://aka.ms/teamsfx-add-appsettings to add following app settings with appropriate value to your Azure environment: 
TEAMSFX_API_CERT_ENDPOINT

You can refer https://aka.ms/teamsfx-connect-api to learn more. 
*/